server:
  port: 8081
spring:
  application:
    name: hmdp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://ip:port/hmdp?useSSL=false&serverTimezone=UTC
    username: username
    password: password
  redis:
    host: ip
    port: 6379
    lettuce:
      # 连接池的配置
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
logging:
  level:
    com.hmdp: debug

# 自定义的配置项
com:
  hmdp:
    resource:
          sms-secret-id: secret-id
          sms-secert-key: secert-key
          sms-sdk-app-id: sdk-app-id
          sms-sign-name: sign-name
          sms-template-id: template-id